package Helpers;

import android.support.annotation.NonNull;

import com.tedxaueb.tedxaueb2017.R;

import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import Models.Speaker;

/**
 * Created by tasos on 3/1/2017.
 */

public class HandleSpeakers {
    private LinkedList<Speaker> myspeakers;
    public LinkedList<Speaker> getMyspeakers(){
        myspeakers=new LinkedList<Speaker>();
        //Hostess
        myspeakers.add(new Speaker("Elena Papadimitriou","Journalist @SKAI.gr","Elena Papadimitriou could not be absent from TEDxAUEB’s 2017 event!\n" +
                "Elena is a journalist at SKAI.gr and will be the hostess of TEDxAUEB's main event second year in a row, as she is considered a core member of our team’s mosaic!", R.drawable.hostess,R.drawable.hostesslarge,"https://www.youtube.com/watch?v=ntVNXCUMSa0","Hostess"));
        //Speakers
        myspeakers.add(new Speaker("Eleftheria Zourou","Founder & CEO of Doctoranytime","Eleftheria Zourou studied Business administration and marketing in University of Piraeus and started her career in Procter and Gamble, where she learned that a good marketer should be in touch with the consumer and get in his shoes, a more formal way to put what she had early enough understood. Then she moved to DOL, where she did marketing for women magazines and having acquired interesting experience from the media world she moved to L’Oreal. Nothing compares to her entrepreneurial life, bringing into life a new fresh idea in the internet/health sector, DOCTORANYTIME.GR. It’s the idea that brings her closer to what she dreamt of: an easier, faster and more patient friendly access to the Greek healthcare system. Eleftheria ‘s first interaction with a “customer” was in the small toy shop of her grandfather, where she understood early enough that sales increase when you sell what consumer needs.",R.drawable.zourou,R.drawable.zouroularge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%CE%B6%CE%BF%CF%8D%CF%81%CE%BF%CF%85/","Speaker"));
        myspeakers.add(new Speaker("Olga Goulandris","Mosaic Media Artist","Olga Goulandris studied in London, History of Art (Birbeck College) and made relevant postgraduate studies (MA, Fine and Decorative Art and Design – Sotheby’s.) She also studied Byzantine and modern techniques of Mosaic in Greece, Italy and the United States. She has 7 solo exhibitions and has participated in several group exhibitions in Greece and abroad. She has numerous awards and recognitions for her unique style and personality in the world of the Mosaic. Olga Goulandris, has managed to highlight the art of mosaic in a way to create a work of art as she does not approach it simply as a folk art. She is the representative of contemporary art of Mosaic in Greece and her works of art are exhibited in museums, galleries and private collections worldwide. The visual artist teaches the art of the mosaic and has created a group of students entitled “Mosaic Κosmos“, which conducts several artistic and charitable actions.",R.drawable.goylandri,R.drawable.goulandrilarg,"http://blog.tedxaueb.com/2017/02/%CF%8C%CE%BB%CE%B3%CE%B1-%CE%B3%CE%BF%CF%85%CE%BB%CE%B1%CE%BD%CE%B4%CF%81%CE%AE/","Speaker"));
        myspeakers.add(new Speaker("Fanis Kollias","Founder & Editor in Chief Solomon","Fanis Kollias is 26 years old, coming from Tripoli. When in 2009 came in Athens to study Business Administration in OPA, the life outside University seemed more interesting, so he decided to start working on the industry before he luxuriated in it, which makes him still a student. He was occupied with events in the cultural sector, journalism in sites and print media, communication, advertising, copywriting and non profit sector, until he was found again at the Athens University of Economics and Business through the Fellowship Diploma of Social Entrepreneurship. This time, he was really devoted and graduated, while he simultaneously started the ”Solomon”, an initiative that focuses on social inclusion and uses the media as a tool.",R.drawable.kollias,R.drawable.kolliaslarge,"http://blog.tedxaueb.com/2017/02/tedxaueb-2017-speakers-%CF%86%CE%AC%CE%BD%CE%B7%CF%82-%CE%BA%CF%8C%CE%BB%CE%BB%CE%B9%CE%B1%CF%82/","Speaker"));
        myspeakers.add(new Speaker("Rain Dove","Model & Activist","Rain Dove is the androgynous/agender model who has been in W, Vogue, Buzzfeed, Elle,Marie Claire, Cosmo, Harper’s Bazaar, Mashable, People and many more. She has created several viral campaigns including a lingerie shoot challenging Victoria Secrets’ Beauty standards which reached over 35 countries. She is known not just as a pretty face, but also as a humanitarian. Her recent video combatting HB2 has garnered millions of views, discovered a previously unexposed illegality to the bill. She also speaks about homelessness and hunger both of which she has experienced herself. Prior to her fashion career, she was a wilderness firefighter and also obtained a BA in Genetic Engineering from UC Berkeley.",R.drawable.rain,R.drawable.rainlarge,"http://blog.tedxaueb.com/2017/02/tedxaueb-2017-speakers-rain-dove/","Speaker"));
        myspeakers.add(new Speaker("Click Ngwere","Migrant feminist activist & knitting artist","Click Ngwere is a migrant feminist activist and knitting artist. She was born in Zimbabwe and took part in the Mozambiki’s guerrilla war as a fighter. After the war, Ngwere continued with her education and she attended the Morgenster Teacher’s College. She became a history teacher and she was trained as a trainer of pre-school teachers in Alvord Training Center. Moreover, she did bee keeping at Henderson Research Station and became a professional bee keeper. Ngwere is a song writer and a gospel singer. She is a dancer of the Mandela Gals group (a female dance troupe from South Africa) in Athens. Since childhood, Ngwere’s dream was to establish a knitting workshop. After years of working in the domestic sector in Greece, she created her own knitting business, Click’s Collection, which produces knitted arts and crafts. Ngwere lives and works in Athens.",R.drawable.click,R.drawable.clicklarge,"http://blog.tedxaueb.com/2017/02/tedxaueb-2017-speakers-click-ngwere/","Speaker"));
        myspeakers.add(new Speaker("Antonis Tsapatakis","Paralympic Champion","At the age of 5 years old, Antonis Tsapatakis began to swim and some years later, he became a polo athlete. In 2005, he joined the Police School, making his dream come true. A year later, in 2006, in a turn of a familiar road, just outside the swimming pool where he had spent half of his life as a water polo player of Chania NO, he lost the control of his motorcycle due to excessive speed. He was ejected against the pavement, resulting in paralysis of the lower limbs. In 2009, he started swimming in the disabled team, under the coaching of Kostas Nikolantonakis. During this time, he has many excellences in national (holds two national records), European and global competitions, he posseses 17 gold, silver and bronze medals. Also, he conducted interviews and professional photographs in Magazines like, Life & Style (2011) and I WEEKLY (2010) .The power, passion and determination led him to the Paralympics in London in 2012, which added to his biographical material, the 4th place in 100m. breaststroke style SB4. The successes continued with the conquest of two bronze medals (50 butterfly, 5,100 front sb4) in the world swimming championship, whick was held in Montreal, Canada in 2013. In 2014, at the European Championship in the Netherlands, he added another silver medal in his collection of 100m. breaststroke sb4. In 2015, at the European Championship in Berlin broke the pan-European record 50m. breaststroke. The same year, in July, in Scotland’s world championship after a stunning race for 100 meters. breaststroke sb4, he returned with the silver medal in his luggage, by breaking his own Panhellenic record by 1.5 second (1.36,30), resulting in his important qualification to the Brazilian Paralympics in Rio in 2016, where he participated in the finals of the 100m. breaststroke style, in SB4 category and finished 4th.",R.drawable.tsapatakis,R.drawable.tsapatakislarge,"http://blog.tedxaueb.com/2017/02/tedxaueb-2017-speakers-t%CF%83%CE%B1%CF%80%CE%B1%CF%84%CE%AC%CE%BA%CE%B7%CF%82/","Speaker"));
        myspeakers.add(new Speaker("Sebastian Erras","Social Media Influencer of Parisian Floors, Photographer","Born in the south of Germany, Sebastian Erras’s interest in photography started during a trip to the Massai Mara in Kenya. Back in Germany, he kept on exploring the local wildlife and was specialized on birds and orchids. Since 2009, he has been a full-member of the GDT (German Wildlife Photographers) and CO-Founder of the GDT Youth Group. Meanwhile, his work has been published in numerous nature and wildlife magazines and in 2010, he won the 2nd prize of the Fritz Pölking Nachwuchspreis der GDT. After having finished his business diploma in Germany, he transformed his passion into work. After his studies in International Marketing, he decided to fulfill his dream and become a fulltime photographer. Having always had a passion for design and architecture, he specialized in the field of interior and architecture photography. Working now for multiple clients all over Europe, he continues living his passion of photography, travel and exploring new things.",R.drawable.erras,R.drawable.erraslarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-sebastian-erras/","Speaker"));
        myspeakers.add(new Speaker("George Dassios","Researcher @Division of Applied Mathematics","George Dasios was born in Patras in 1946, where he attended primary and secondary schools. In 1965, he was accepted at the Mathematics Department of the University of Athens. He got Masters in 1972 and PhD in 1975 in Applied Mathematics from the University of Illinois at Chicago. He has worked as an assistant at the Department of Mathematics, of the University of Patras and in 1980 he was entitled as lecturer of Applied Mathematics at the National Technical University. In 1981, at the age of 35, he was elected professor in the Mathematics Department of the University of Patras and in 1989, he accepted the invitation of the Department of Chemical Engineering at the same university. He has taught and been invited to give research seminars in more than 100 universities mainly in the US and Europe, but also in other countries such as Japan, Korea, Finland, Brazil and others. His writing work, includes 155 research papers, published in major international journals. He was scientific director of PANEGKO, a program related to early diagnosis traumatic brain injury and the recognition of the particle shape in biological suspensions. His work on the problem of magnetoencephalography in elliptical geometry, was awarded by the Academy of Athens in 2004. For his research on the electromagnetic activity of the brain, he was awarded by the European Union, one of the 15 honorary “Chairs-Excellence Marie Curie» that were given worldwide, independently of the specialty in 2005. Finally, he has 25 years of involvement in examination commitees of the Ministry of Education, of the State Scholarships Foundation and the Supreme Personnel Selection Council.",R.drawable.dasios,R.drawable.dasioslarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%CE%B3%CE%B9%CF%8E%CF%81%CE%B3%CE%BF%CF%82-%CE%B4%CE%AC%CF%83%CE%B9%CE%BF%CF%82/","Speaker"));
        myspeakers.add(new Speaker("Antonis Ntzegkoutanis","Tattoo artist & Graduate of Athens School of Fine Arts","Antonis Ntzegkoutanis is a tattoo artist. He has worked in the FTW Tattoo Studio and has participated in two Tattoo Conventions in Thessaloniki and Cyprus respectively. In 2016, he became the first graduate of the Athens School of Fine Arts (ASFA) to show his tattoo work in his thesis exhibition. This exhibition, constituted a recognition for the art of tattoo in our country while, at the same time, contributed to the expansion of the perception of what is considered to be modern art. His tattoos are characterized by a mixture of realism, abstract patterns, writings and intense line drawings. He is also interested in photography and painting.",R.drawable.njegkountanis,R.drawable.njegkountanislarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%CE%B1%CE%BD%CF%84%CF%8E%CE%BD%CE%B7%CF%82-%CE%BD%CF%84%CE%B6%CE%B5%CE%B3%CE%BA%CE%BF%CF%85%CF%84%CE%AC%CE%BD%CE%B7%CF%82/","Speaker"));
        myspeakers.add(new Speaker("Marie Halaka","Fundraising Director &Strategic CSR Developement at PRAKSIS","Marie Halaka was born in Panama in 1966 and she is multilingual (French, English, Spanish and Greek). She holds a Baccalaureat in Lettres et Philosophie and a degree in Business Administration and Marketing. Marie Halaka is currently Fundraising Director and Strategic CSR Development at PRAKSIS, major Greek NGO. In the past, she has concluded several contracts on electricity imports as a trader.  She has served as a Commercial Director for 12 years (Avepe SA, Neoset), managing strategic partnerships in Greece and abroad, (Steelcase Inc.) and excelling in business development. She has also, conducted a multitude of lectures organized a multitude of fundraising events such as the « Philellenes Hollywood Gala» in Los Angeles.",R.drawable.halaka,R.drawable.halakalarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%ce%bc%ce%b1%cf%81%ce%af-%cf%87%ce%ac%ce%bb%ce%b1%ce%ba%ce%b1/","Speaker"));
        myspeakers.add(new Speaker("Ioanna Sapfo Pepelasis","Associate Professor of Economic History & Founder of Take off Greece","oanna Sapfo Pepelasis, a graduate of Harvard and the LSE, is Associate Professor of Economic History at the Department of Economics at Athens University of Economics and Business (AUEB).She has taught economic history and entrepreneurship courses at an undergraduate and graduate level at AUEB and the University of Athens. She has served on the editorial Boards of International Journals and has received a prize from the Ottoman Bank Archive for an article on Greek Diaspora Bankers in 2003. She heads a research project titled ‘History of Entrepreneurship and the Greek Corporate Sector ’ and is writing the history of the Greek corporate sector. At the moment, her research is focusing on international comparisons in the history of the joint stock company and the new business model which is arising in Greece during the current economic crisis. She has organised international conferences and has served on the board of the European Business History Association and the European Association of Evolutionary Political Economy. She is a mentor at the Athens Center for Entrepreneurship and Innovation. She has also served as a member of the board of the directors of the Greek Centre for Planning and Economic Research, 2010-2013 and in 2015, she founded the ”Take Off Greece” a support team for entrepreneurship for people over 40 years old.",R.drawable.pepelasi,R.drawable.pepelasilarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%CE%B9%CF%89%CE%AC%CE%BD%CE%BD%CE%B1-%CF%83%CE%B1%CF%80%CF%86%CF%8E-%CF%80%CE%B5%CF%80%CE%B5%CE%BB%CE%AC%CF%83%CE%B7/","Speaker"));
        myspeakers.add(new Speaker("Nasia Paschaleri","Co Founder @FoodSherlocks, Nutritionist Gerontologist @Frontizo nursing home","Nasia Paschaleri is a dietitian specialized in Gerontology (MSc Gerontology). She completed her bachelor studies at the department of Nutrition and Dietetics of Alexander Technological Institute in Thessaloniki. Having achieved a scholarship, she then received her Master’s degree in Gerontology from the University of Southampton in the United Kingdom. Currently she is a PhD candidate at the department of Medicine of University of Crete. She is the co-partner of nutrition and anti-aging center ‘Natural Health Clinic’ (www.naturalhealthclinic.gr) and she is also, an executive board member of the elderly care unit ‘Frontizo’ (www.frontizw.gr) in Thessaloniki. Since 2014, she is appointed as a dietician at the diagnostic centers of Euromedica group in Kifissia and Galatsi in Athens. Together with Irene Paschaleri, biologist specializing in nutrition, she is the co-founder of the project ‘Food Sherlocks’. This project, is a nutrition guide focusing on healthy and individualized menu options when eating out. ‘Food Sherlocks’ is provided through a website and smartphone application (www.foodsherlocks.com). She has an active participation in conferences in Greece and abroad and she is a permanent collaborator with numerous magazines, newspapers and websites.",R.drawable.paschalieri,R.drawable.paschalierilarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-speakers-%CE%BD%CE%AC%CF%83%CE%B9%CE%B1-%CF%80%CE%B1%CF%83%CF%87%CE%B1%CE%BB%CE%AD%CF%81%CE%B7/","Speaker"));

        //Performances
        myspeakers.add(new Speaker("Yanna Vasileiou", "Musician, Signer, Compositor & Songwriter","Yanna Vasileiou is a musician, singer, composer and songwriter. She was born and raised in Athens, but she also has Constantinople roots She is a graduate of the Music Department of the National Kapodistrian University of Athens and holds “A” level diplomas in classical piano, harmony, counterpoint and fugue.  Her first original song is “Logia Agapis” (Words of Love), which she composed, wrote the lyrics and performs herself. Her complete album “Ola Osa Agapo” was on the Top spot in iTunes.From that stood out the songs “Miazei Apl0” and “Kathe Fora pou tha Rtheis Vrexei“. She undertook the lyrics rendition and the vocal teaching in the musical “Rocky Horror Show” and “Froutopia” at Rex theater and in the “As Erhosoun gia ligo” at Acropole.",R.drawable.gianna,R.drawable.giannalarge,"http://blog.tedxaueb.com/2017/02/tedxaueb-2017-performances-%CE%B3%CE%B9%CE%AC%CE%BD%CE%BD%CE%B1-%CE%B2%CE%B1%CF%83%CE%B9%CE%BB%CE%B5%CE%AF%CE%BF%CF%85/","Performance"));
        myspeakers.add(new Speaker("Thomas Zampras","Stand-up Comedian","Οur first performer is Thomas Zampras. Born and raised in Trikala. He came to Athens to study International and European Studies at the University of Piraeus but eventually, he chose comedy. Before he settled down, heσ worked on music criticism and filmmaking workshops, but it all became clear when he came first in a stand up comedy competition. He makes stand up performances all over Greece, writes in Oneman, while he was scriptwriting and playing at the TV show Cinelthete at SKAI.",R.drawable.zampras,R.drawable.zampraslarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-performances-%CE%B8%CF%89%CE%BC%CE%AC%CF%82-%CE%B6%CE%AC%CE%BC%CF%80%CF%81%CE%B1%CF%82/","Performance"));
        myspeakers.add(new Speaker("Fysalida","Dance Group","Fysalida is a dance group based in Heraklion, Crete. The company was founded in 2006 by Georgia Petrali with the aim of exploring, creating and producing any art form through collaboration between artists, educators, therapists and scientists. The objective of the Fysalida dance company’s activities is to move the public via the art produced and to raise awareness about various modern social issues which are highlighted via the art they produce. The dance company’s activities include dance and dance-theatre performances, solo performances, dance film and video art production, installation performances, experimental performances and video screenings, modern dance, movement, contact improvisation seminars, community work projects and community dance projects. The company’s research and creative materials are transformed into art through movement, dance, speech, theatre, photography, music, the visual arts and video art.",R.drawable.fysalida,R.drawable.fysalidalarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-performances-%CF%86%CF%85%CF%83%CE%B1%CE%BB%CE%AF%CE%B4%CE%B1/","Performance"));
        myspeakers.add(new Speaker("On Stage","Music Theater Team","On Stage musical theater was created in 2010 in order to aqcaint the art of musical theater. So, it became the door for anyone who loves the performing arts. Working with the culture of the music theater, the quality of art and the severity of the disciplined work, On Stage musical theater managed to train many talented people and lead them to their professional career in Greece and abroad. The aim is, this integrated form of art to be used as a way of approaching the inner world of the student,  in order fot the performer to find the best part of himself and shine. The On Stage Ptofessionals is the official musical group of On Stage and the first professional musical theater group in Greece. The group consists of professionals singers and people with developed performance with singing, dancing and acting.",R.drawable.onstage,R.drawable.onstagelarge,"http://blog.tedxaueb.com/2017/03/tedxaueb-2017-performances-on-stage-musical-theater/","Performance"));
        /*myspeakers.add(new Speaker());
        myspeakers.add(new Speaker());
        myspeakers.add(new Speaker());*/

        return myspeakers;
    }
}
